### ISSUE TITLE
"Setup local environment" step results in error

### ISSUE THREAD

**Issue by gaydenko** [amient/hello-kafka-streams#5]
Hi!

After pulling kafka I have copied/pasted from README.md the string `./gralew install` - boom!.. `d` char is missed. Ok, after fixing the typo I get: 

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

Have I missed something? 
Gradle 2.12 is installed under Arch Linux.

**Comment by michal-harish** [comment]
Hi, you need to run `gradle` in the Kafka source dir before running `./gradlew install` - I have updated the README (and fixed the typo), thanks! Try and if you encounter some other problem continue in this thread, otherwise close, thanks.

**Comment by gaydenko** [comment]
Thanks! - now `gradlew` finishes with success. But zookeeper start results in `Error: Could not find or load main class org.apache.zookeeper.server.quorum.QuorumPeerMain`. Have I missed some presumed pre-requirements? 

I guess some steps is missed as far as official binary distribution contains `libs` directory, while pulled one doesn't.

**Comment by michal-harish** [comment]
Looks like  you're running on windows. in that case you need to use `zookeeper-server-start.bat` and `kafka-server-start.bat` respectively instead of the bash scripts. I will update the instructions for windows users..

**Comment by gaydenko** [comment]
What are these windows? :) No, as I have mentioned, I run Arch Linux.

**Comment by michal-harish** [comment]
I see (missed the linux mention). I have just tried on a new user (on mac) and it worked - could be that you may need to run `./gradlew jar install` - going to try on a linux vm and will update.

**Comment by gaydenko** [comment]
I guess `-PscalaVersion=2.11` options was needed. Now I have already created all topics. But can not build the project istself: 

```
 $ ./gradlew build
:compileJava/some/dir/hello-kafka-streams/src/main/java/org/apache/kafka/connect/api/ConnectEmbedded.java:76: error: no suitable constructor found for DistributedHerder(DistributedConfig,Time,Worker,StatusBackingStore,String)
        herder = new DistributedHerder(config, time, worker, statusBackingStore, "");
                 ^
    constructor DistributedHerder.DistributedHerder(DistributedConfig,Time,Worker,StatusBackingStore,ConfigBackingStore,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor DistributedHerder.DistributedHerder(DistributedConfig,Worker,String,StatusBackingStore,ConfigBackingStore,WorkerGroupMember,String,Time) is not applicable
      (actual and formal argument lists differ in length)
1 error
 FAILED
```

**Comment by michal-harish** [comment]
Yes, -PscalaVersion-2.11 was missing - have added. The last error is probably because kafka trunk has changed since the demo was written (it moves fast). Looking at it

**Comment by gaydenko** [comment]
Probably it takes some sense to checkout concrete `kafka` commit to become free from constant updating the project to be in sync with kafka trunk.

**Comment by michal-harish** [comment]
Either that, or use 0.10.0.0 tag which has release candidates already so will be more-less stable.

**Comment by gaydenko** [comment]
Ok, will try and report, thanks.

**Comment by gaydenko** [comment]
@michal-harish ,

Yes! - all OK is now with 0.10.00 tag, thanks!

```
USER: KasparBot num.edits: 1
USER: Warairarepano&Guaicaipuro num.edits: 1
USER: AnomieBOT num.edits: 1
USER: .185.180.212 num.edits: 1
USER: 1.62.222.240 num.edits: 1
USER: Iamluke16 num.edits: 1
USER: Raymarcbadz num.edits: 1
USER: Nyuszika7H num.edits: 1
USER: ShelleyAdams num.edits: 1
USER: Jayventt num.edits: 1
USER: .219.222.41 num.edits: 1
USER: Ian Balchin num.edits: 1
USER: .108.156.200 num.edits: 1
USER: Richhoncho num.edits: 1
USER: 1.117.13.231 num.edits: 1
USER: Jonney2000 num.edi...
```

**Comment by michal-harish** [comment]
Cool, thanks for your time - others will have it easier! I will update the master build and instructions to use 0.10.0.0 instead of trunk..

**Comment by phderome** [comment]
I am apparently getting same build compile error as described Apr 22 on "new DistributedHerder" and my build.gradle file shows ext.kafkaVersion = '0.10.0.0'. I used git clone on https://github.com/amient/hello-kafka-streams.git. I have two compile errors, that's second one whereas first one says:
JsonPOJOSerde.java:28: error: JsonPOJOSerde is not abstract and does not override abstract method close

I am on OSX Capitan.

**Comment by michal-harish** [comment]
Hi. Yes, I have just tried (deleted my 0.10.0.0 jars) and it fails. There
must have been changes in the kafka 0.10 release back-ported onto the
0.10.0.0 release. I'll update the hello program tonight.

**Comment by phderome** [comment]
much appreciated. I am not pushing you on a deadline, it's Sunday and it's
free.

**Comment by michal-harish** [comment]
it should work on master now - confluent platform branch still needs updating for their 3.0 platform release.

**Comment by phderome** [comment]
yes, thanks!

**Comment by phderome** [comment]
I see proper behaviour at run-time but previously there were quite a few
Java exception traces about files not being there. Am I doing something
visibly wrong?

WARN could not create Dir using jarFile from url
file:/Users/philippederome/workspace/hello-kafka-streams/build/lib/jersey-container-servlet-core-2.22.2.jar.
skipping. (org.reflections.Reflections:104)

java.lang.NullPointerException

at java.util.zip.ZipFile.<init>(ZipFile.java:207)

at java.util.zip.ZipFile.<init>(ZipFile.java:149)

at java.util.jar.JarFile.<init>(JarFile.java:166)

at java.util.jar.JarFile.<init>(JarFile.java:130)

at org.reflections.vfs.Vfs$DefaultUrlTypes$1.createDir(Vfs.java:212)

at org.reflections.vfs.Vfs.fromURL(Vfs.java:99)

at org.reflections.vfs.Vfs.fromURL(Vfs.java:91)

at org.reflections.Reflections.scan(Reflections.java:237)

at org.reflections.Reflections.scan(Reflections.java:204)

at org.reflections.Reflections.<init>(Reflections.java:129)

at
org.apache.kafka.connect.runtime.AbstractHerder.connectorPlugins(AbstractHerder.java:268)

at
org.apache.kafka.connect.runtime.AbstractHerder$1.run(AbstractHerder.java:377)

at java.lang.Thread.run(Thread.java:745)

WARN could not create Vfs.Dir from url. ignoring the exception and
continuing (org.reflections.Reflections:208)

org.reflections.ReflectionsException: Could not open url connection

at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:37)

at org.reflections.vfs.JarInputDir$1.iterator(JarInputDir.java:33)

at org.reflections.Reflections.scan(Reflections.java:240)

at org.reflections.Reflections.scan(Reflections.java:204)

at org.reflections.Reflections.<init>(Reflections.java:129)

at
org.apache.kafka.connect.runtime.AbstractHerder.connectorPlugins(AbstractHerder.java:268)

at
org.apache.kafka.connect.runtime.AbstractHerder$1.run(AbstractHerder.java:377)

at java.lang.Thread.run(Thread.java:745)

Caused by: java.io.FileNotFoundException:
/Users/philippederome/workspace/hello-kafka-streams/build/lib/jersey-container-servlet-core-2.22.2.jar
(No such file or directory)

at java.io.FileInputStream.open0(Native Method)

at java.io.FileInputStream.open(FileInputStream.java:195)

at java.io.FileInputStream.<init>(FileInputStream.java:138)

at java.io.FileInputStream.<init>(FileInputStream.java:93)

at
sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)

at
sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)

at org.reflections.vfs.JarInputDir$1$1.<init>(JarInputDir.java:36)

... 7 more

INFO Reflections took 2991 ms to scan 1 urls, producing 2196 keys and 9907
values  (org.reflections.Reflections:229)

USER: Look2See1 num.edits: 1

USER: Dcirovic num.edits: 1

USER: gandhi num.edits: 1

USER: 5.140.88.205 num.edits: 1

USER: .121.50.217 num.edits: 1

USER: FamblyCat94 num.edits: 1

USER: Andidimatteo num.edits: 1

USER: Primaler num.edits: 1

USER: EchetusXe num.edits: 1

USER: LilHelpa num.edits: 1

USER: Josve05a num.edits: 1

USER: A02:C7F:9817:8E00:34BB:312:5EC1:C7EE num.edits: 1

USER: Forestfrolic num.edits: 1

USER: PrideOfPortree num.edits: 1

USER: Josve05a num.edits: 2

USER: Gamble1993 num.edits: 1

USER: Dcirovic num.edits: 2

**Comment by michal-harish** [comment]
You're not doing anything wrong. I've seen those too first time I run it -
I suspect some Reflections incompatibility. I will take a look at this when
I'll be upgrading the cp branch.

**Comment by phderome** [comment]
ok, I'll just play around with it now and not worry.
